#pragma once

#include <iostream>
#include <string>
#include <sstream>
#include <algorithm>
#include <stdexcept>
#include <regex>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <vector>
#include <netdb.h>
#include <cstring>
#include <thread>
#include <unordered_map>
#include <fstream>
#include <cstdio>
#include <chrono>